spring:
  application:
    name: restaurant-erp

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/food_erp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info