spring:
  application:
    name: restaurant-erp

  datasource:
    url: ${DB_URL:jdbc:h2:mem:food_erp;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  flyway:
    enabled: ${FLYWAY_ENABLED:false}

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info